
services:
  backend:
    build: ./backend
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - SHORT_BASE_URL=https://iatools.fun/
    ports:
      - "80:5000"
    volumes:
      - ./backend:/app
      - ./models:/app/models
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: